### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by ppsh41** [liuli-moe/pmas#4]
ch209最后一段行动策略不明，在英文文本中未见，我去sv看了原文也未看见，需检查来源及确认是否需保留在译文中

**Comment by rxliuli** [comment]
感谢提醒，已修复并更新至线上。

---

有一些人名在翻译的时候吾辈也很头疼，因为原文中也一直存在变动和不一致，例如 晴（Haru） 和 晴奈（Haruna），还没来得及细看。如果有遇到任何错误，欢迎提更多的 issue，当然，更欢迎提 pr 来直接修复它

**Comment by ppsh41** [comment]
> 感谢提醒，已修复并更新至线上。
> 
> 有一些人名在翻译的时候吾辈也很头疼，因为原文中也一直存在变动和不一致，例如 晴（Haru） 和 晴奈（Haruna），还没来得及细看。如果有遇到任何错误，欢迎提更多的 issue，当然，更欢迎提 pr 来直接修复它

如同我的pr，我确认有问题的地方已经改了；
不过这个地方原文完全没看见，但又和上文逻辑非常一致，不知道什么情况，所以才提issue想知道来源以及确认处理方式

**Comment by rxliuli** [comment]
来源是 claude 有时不能正确的理解这是个翻译任务，遇到 write 的时候，它有时会以为是续写。。。
